apiVersion: v1
kind: Template

metadata:
  name: react-web-app
  annotations:
    iconClass: icon-jboss
    tags: react, web app
    description: Serving a react web app on Nginx

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: react-web-app-nginx
    spec: {}

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: nginx-image-runtime
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: 'centos/nginx-112-centos7:latest'

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: react-web-app-nginx
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: react-web-app-nginx:latest
      postCommit: {}
      resources: {}
      source:
        type: Image
        images:
          - from:
              kind: ImageStreamTag
              name: react-web-app-builder:latest
            paths:
              - destinationDir: .
                sourcePath: /opt/app-root/output/.
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: nginx-image-runtime:latest
          incremental: true
        type: Source
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: ImageChange
          imageChange:
            from:
              kind: ImageStreamTag
              name: react-web-app-builder:latest
    status:
      lastVersion: 0

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: react-web-app
      name: react-web-app
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: react-web-app
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: react-web-app
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: react-web-app-nginx
              imagePullPolicy: IfNotPresent
              name: react-web-app-nginx
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - react-web-app-nginx
            from:
              kind: ImageStreamTag
              name: 'react-web-app-nginx:latest'

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: react-web-app
      name: react-web-app
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: react-web-app

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: react-web-app
      name: react-web-app
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: react-web-app